# Generated by Django 5.0.8 on 2024-08-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_climates_terrain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("population", models.IntegerField(blank=True, null=True)),
                (
                    "climates",
                    models.ManyToManyField(
                        blank=True, related_name="planets", to="core.climates"
                    ),
                ),
                (
                    "terrains",
                    models.ManyToManyField(
                        blank=True, related_name="planets", to="core.terrain"
                    ),
                ),
            ],
        ),
    ]
