# Generated by Django 5.0.8 on 2024-08-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_planets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planets",
            name="population",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
